In [1]:
import pandas as pd

## Reading Data

In [2]:
df=pd.read_csv('data1.csv')

In [3]:
df.head()

Fever  Bodypain  Age  RunnyNose  DiffBreath  InfectionProb
0   98.691178         1   67          1           0              1
1  101.119583         0   18          1           1              1
2   99.252314         1   67          1           0              1
3  100.323703         0   57          1           0              1
4   99.062927         1   67          1           0              1

In [4]:
df.tail()

Fever  Bodypain  Age  RunnyNose  DiffBreath  InfectionProb
2994   99.458333         1   67          1           0              1
2995   99.879224         0   85          0           0              0
2996  100.068380         1   67          1           0              1
2997   99.194195         0   28          0           0              0
2998  100.117306         1   67          1           0              1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2999 entries, 0 to 2998
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Fever          2999 non-null   float64
 1   Bodypain       2999 non-null   int64  
 2   Age            2999 non-null   int64  
 3   RunnyNose      2999 non-null   int64  
 4   DiffBreath     2999 non-null   int64  
 5   InfectionProb  2999 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 140.7 KB


In [6]:
df['DiffBreath'].value_counts()

 0    2007
 1     520
-1     472
Name: DiffBreath, dtype: int64

In [7]:
df.describe()

Fever     Bodypain          Age    RunnyNose   DiffBreath  \
count  2999.000000  2999.000000  2999.000000  2999.000000  2999.000000   
mean     99.976152     0.740914    58.712904     0.742581     0.016005   
std       1.164206     0.438206    21.919342     0.437285     0.575005   
min      98.001246     0.000000     1.000000     0.000000    -1.000000   
25%      98.972635     0.000000    49.000000     0.000000     0.000000   
50%      99.953753     1.000000    67.000000     1.000000     0.000000   
75%     100.977855     1.000000    67.000000     1.000000     0.000000   
max     101.998543     1.000000   100.000000     1.000000     1.000000   

       InfectionProb  
count    2999.000000  
mean        0.752918  
std         0.431387  
min         0.000000  
25%         1.000000  
50%         1.000000  
75%         1.000000  
max         1.000000

## Train Test Splitting

In [8]:
import numpy as np

In [9]:
def data_split(data, ratio):
    np.random.seed(42)
    shuffled=np.random.permutation(len(data))
    test_set_size=int(len(data) * ratio)
    test_indices=shuffled[:test_set_size]
    train_indices=shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[train_indices]
    

In [10]:
np.random.permutation(9)

array([3, 7, 2, 5, 6, 0, 8, 4, 1])

In [11]:
train,test=data_split(df, 0.2)

In [12]:
train

Fever  Bodypain  Age  RunnyNose  DiffBreath  InfectionProb
1103  100.215910         0   46          1          -1              0
1569   99.036496         1   30          1           0              0
2229   99.872107         1   70          0           0              0
2296   99.013397         1   67          1           0              1
1800   98.563897         1   67          1           0              1
...          ...       ...  ...        ...         ...            ...
1638  101.011409         1   67          1           0              1
1095   99.359787         1   18          0           0              0
1130  101.647540         1   67          1           0              1
1294  101.071705         1   67          1           0              1
860   101.281800         1   67          1           0              1

[2400 rows x 6 columns]

In [13]:
test

Fever  Bodypain  Age  RunnyNose  DiffBreath  InfectionProb
1103  100.215910         0   46          1          -1              0
1569   99.036496         1   30          1           0              0
2229   99.872107         1   70          0           0              0
2296   99.013397         1   67          1           0              1
1800   98.563897         1   67          1           0              1
...          ...       ...  ...        ...         ...            ...
1638  101.011409         1   67          1           0              1
1095   99.359787         1   18          0           0              0
1130  101.647540         1   67          1           0              1
1294  101.071705         1   67          1           0              1
860   101.281800         1   67          1           0              1

[2400 rows x 6 columns]

In [14]:
X_train=train[['Fever','Bodypain','Age','RunnyNose','DiffBreath']].to_numpy()
X_test=test[['Fever','Bodypain','Age','RunnyNose','DiffBreath']].to_numpy()


In [15]:
Y_train=train[['InfectionProb']].to_numpy().reshape(2400)
Y_test=test[['InfectionProb']].to_numpy().reshape(2400)


In [16]:
Y_train

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
clf= LogisticRegression()
clf.fit(X_train, Y_train)

LogisticRegression()

In [19]:
clf.predict_proba([[100, 1, 22, 1, 1]])

array([[0.1886114, 0.8113886]])

In [20]:
inputFeatures=[100, 1, 22, -1, 1]
infProb=clf.predict_proba([inputFeatures])[0][1]

In [21]:
infProb

0.2824766873675629